name: Build and Release Android Clara Speaker App

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name:  checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Build Signed APK
        run: |
          ./gradlew assembleRelease \
            -PsigningKeyBase64="${{ secrets.SIGNING_KEY_BASE64 }}" \
            -PkeystorePassword="${{ secrets.KEYSTORE_PASSWORD }}" \
            -PkeyAlias="${{ secrets.KEY_ALIAS }}" \
            -PkeyPassword="${{ secrets.KEY_PASSWORD }}"
        
      - name: Generate Tag Name
        id: tag
        run: echo "RELEASE_TAG=v$(date -u +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
        
      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
